/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OrderOfService;

/**
 *
 * @author natha
 */
public class CreateServiceMain extends javax.swing.JFrame {
    
    /**
     * Creates new form CreateServiceMain
     */
    public CreateServiceMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        lTitle = new javax.swing.JLabel();
        AutoCreatePanel = new javax.swing.JPanel();
        lSubTitle = new javax.swing.JLabel();
        tfNoSongs = new javax.swing.JTextField();
        tfTag = new javax.swing.JTextField();
        tfSpeaker = new javax.swing.JTextField();
        lNoSongs = new javax.swing.JLabel();
        lTagTheme = new javax.swing.JLabel();
        lSpeaker = new javax.swing.JLabel();
        bAutoCreate = new javax.swing.JButton();
        bManualCreate = new javax.swing.JButton();
        lLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GWBC Order of Service Manager - Create Service");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(218, 227, 243));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 114, 196), 2));

        lTitle.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        lTitle.setForeground(new java.awt.Color(31, 56, 100));
        lTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitle.setText("GWBC Create Service");

        AutoCreatePanel.setBackground(new java.awt.Color(218, 227, 243));
        AutoCreatePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 114, 196), 2));

        lSubTitle.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lSubTitle.setForeground(new java.awt.Color(31, 56, 100));
        lSubTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lSubTitle.setText("Create Service Automatically");

        tfNoSongs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNoSongsKeyTyped(evt);
            }
        });

        lNoSongs.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        lNoSongs.setForeground(new java.awt.Color(31, 56, 100));
        lNoSongs.setText("Number of songs:");

        lTagTheme.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        lTagTheme.setForeground(new java.awt.Color(31, 56, 100));
        lTagTheme.setText("Service Tag/Theme:");

        lSpeaker.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        lSpeaker.setForeground(new java.awt.Color(31, 56, 100));
        lSpeaker.setText("Speaker:");

        bAutoCreate.setBackground(new java.awt.Color(180, 199, 231));
        bAutoCreate.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        bAutoCreate.setForeground(new java.awt.Color(31, 56, 100));
        bAutoCreate.setText("Create Automatically");
        bAutoCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAutoCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AutoCreatePanelLayout = new javax.swing.GroupLayout(AutoCreatePanel);
        AutoCreatePanel.setLayout(AutoCreatePanelLayout);
        AutoCreatePanelLayout.setHorizontalGroup(
            AutoCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lSubTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(AutoCreatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AutoCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNoSongs)
                    .addComponent(lTagTheme)
                    .addComponent(lSpeaker))
                .addGap(39, 39, 39)
                .addGroup(AutoCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfSpeaker, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(tfTag)
                    .addComponent(tfNoSongs))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AutoCreatePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bAutoCreate)
                .addContainerGap())
        );
        AutoCreatePanelLayout.setVerticalGroup(
            AutoCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AutoCreatePanelLayout.createSequentialGroup()
                .addComponent(lSubTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AutoCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNoSongs, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNoSongs))
                .addGap(18, 18, 18)
                .addGroup(AutoCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTag, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTagTheme))
                .addGap(18, 18, 18)
                .addGroup(AutoCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSpeaker, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSpeaker))
                .addGap(18, 18, 18)
                .addComponent(bAutoCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        bManualCreate.setBackground(new java.awt.Color(180, 199, 231));
        bManualCreate.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        bManualCreate.setForeground(new java.awt.Color(31, 56, 100));
        bManualCreate.setText("Create Manually Instead");
        bManualCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bManualCreateActionPerformed(evt);
            }
        });

        lLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrderOfService/GWBC Logo.png"))); // NOI18N

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AutoCreatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(bManualCreate)
                .addGap(107, 107, 107)
                .addComponent(lLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(lTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AutoCreatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bManualCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lLogo))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Action Listener for the Create Service Automatic function
     * Creates a service automatically
     * @param evt 
     */
    private void bAutoCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAutoCreateActionPerformed
        //If the text field for numSongs is empty don't go ahead
        if(tfNoSongs.getText().isEmpty()) {
            //Create UserMessageBox informing of error
            UserMessageBox myMessage = new UserMessageBox();
            myMessage.setTitle("Need input");
            myMessage.setMessage("You have not said how many songs. \n"
                    + "Therefore, the service has not been created");
        }
        else {
            //Set the parameters that will be used
            int numSongs = Integer.parseInt(tfNoSongs.getText());
            String Tag = tfTag.getText();
            String Speaker = tfSpeaker.getText();
            
            //Create the object
            CreateServiceAutomatic autoCreate = new CreateServiceAutomatic(numSongs, Tag, Speaker);
        }
    }//GEN-LAST:event_bAutoCreateActionPerformed

    /**
     * Creates a CreateServiceManual form and closes this form
     * @param evt 
     */
    private void bManualCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bManualCreateActionPerformed
        CreateServiceManual createService =  new CreateServiceManual();
        createService.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_bManualCreateActionPerformed

    /**
     * Key Listener ensuring that the input for tfNoSongs is numeric
     * @param evt 
     */
    private void tfNoSongsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNoSongsKeyTyped
        char inChar = evt.getKeyChar();
        
        if(Character.isDigit(inChar) == false) {
            evt.consume();
        }
    }//GEN-LAST:event_tfNoSongsKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateServiceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateServiceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateServiceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateServiceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateServiceMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AutoCreatePanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton bAutoCreate;
    private javax.swing.JButton bManualCreate;
    private javax.swing.JLabel lLogo;
    private javax.swing.JLabel lNoSongs;
    private javax.swing.JLabel lSpeaker;
    private javax.swing.JLabel lSubTitle;
    private javax.swing.JLabel lTagTheme;
    private javax.swing.JLabel lTitle;
    private javax.swing.JTextField tfNoSongs;
    private javax.swing.JTextField tfSpeaker;
    private javax.swing.JTextField tfTag;
    // End of variables declaration//GEN-END:variables
}
