/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OrderOfService;

import javax.swing.JFrame;

/**
 * The main frame for the application
 *
 * @author nathan deverill
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lTitle = new javax.swing.JLabel();
        lLogo = new javax.swing.JLabel();
        bCreateService = new javax.swing.JButton();
        bAddItems = new javax.swing.JButton();
        bEditItems = new javax.swing.JButton();
        bDeleteItems = new javax.swing.JButton();
        bReviewServices = new javax.swing.JButton();
        bReviewSongs = new javax.swing.JButton();
        bExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GWBC Order of Service Manager");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(218, 227, 243));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 114, 196), 2));

        lTitle.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        lTitle.setForeground(new java.awt.Color(31, 56, 100));
        lTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitle.setText("GWBC Order of Service Manager");

        lLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrderOfService/GWBC Logo.png"))); // NOI18N

        bCreateService.setBackground(new java.awt.Color(180, 199, 231));
        bCreateService.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        bCreateService.setForeground(new java.awt.Color(31, 56, 100));
        bCreateService.setText("Create Service");
        bCreateService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCreateServiceActionPerformed(evt);
            }
        });

        bAddItems.setBackground(new java.awt.Color(180, 199, 231));
        bAddItems.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        bAddItems.setForeground(new java.awt.Color(31, 56, 100));
        bAddItems.setText("Add Items");
        bAddItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddItemsActionPerformed(evt);
            }
        });

        bEditItems.setBackground(new java.awt.Color(180, 199, 231));
        bEditItems.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        bEditItems.setForeground(new java.awt.Color(31, 56, 100));
        bEditItems.setText("Edit Items");
        bEditItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditItemsActionPerformed(evt);
            }
        });

        bDeleteItems.setBackground(new java.awt.Color(180, 199, 231));
        bDeleteItems.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        bDeleteItems.setForeground(new java.awt.Color(31, 56, 100));
        bDeleteItems.setText("Delete Items");
        bDeleteItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteItemsActionPerformed(evt);
            }
        });

        bReviewServices.setBackground(new java.awt.Color(180, 199, 231));
        bReviewServices.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        bReviewServices.setForeground(new java.awt.Color(31, 56, 100));
        bReviewServices.setText("Review Services");
        bReviewServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReviewServicesActionPerformed(evt);
            }
        });

        bReviewSongs.setBackground(new java.awt.Color(180, 199, 231));
        bReviewSongs.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        bReviewSongs.setForeground(new java.awt.Color(31, 56, 100));
        bReviewSongs.setText("Review Songs");
        bReviewSongs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReviewSongsActionPerformed(evt);
            }
        });

        bExit.setBackground(new java.awt.Color(180, 199, 231));
        bExit.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        bExit.setForeground(new java.awt.Color(31, 56, 100));
        bExit.setText("Exit");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bCreateService, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(bAddItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bEditItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bDeleteItems, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bReviewServices, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(bReviewSongs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lLogo)
                        .addGap(21, 21, 21))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCreateService, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bReviewServices, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAddItems, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bReviewSongs, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEditItems, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bExit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(bDeleteItems, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(55, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lLogo)
                        .addGap(35, 35, 35))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Pressing of the button should exit the whole program
     * @param evt 
     */
    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bExitActionPerformed

    /**
     * Opens the class/form CreateServiceMain so the user can create a service
     * @param evt 
     */
    private void bCreateServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCreateServiceActionPerformed
        CreateServiceMain createService =  new CreateServiceMain();
        createService.setVisible(true);
    }//GEN-LAST:event_bCreateServiceActionPerformed

    /**
     * Opens the AddItemsMain Form so the user can add items to the database
     * @param evt 
     */
    private void bAddItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddItemsActionPerformed
        AddItemsMain addItems = new AddItemsMain();
        addItems.setVisible(true);
    }//GEN-LAST:event_bAddItemsActionPerformed

    /**
     * Opens the EditItemsMain Form so the user can edit items in the database
     * @param evt 
     */
    private void bEditItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditItemsActionPerformed
        EditItemsMain editItems = new EditItemsMain();
        editItems.setVisible(true);
    }//GEN-LAST:event_bEditItemsActionPerformed

    /**
     * Opens the DeleteItemsMain Form so the user can remove records from the database
     * @param evt 
     */
    private void bDeleteItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteItemsActionPerformed
        DeleteItemsMain deleteItems = new DeleteItemsMain();
        deleteItems.setVisible(true);
    }//GEN-LAST:event_bDeleteItemsActionPerformed

    /**
     * Opens the ReviewServices Form so the user can review services
     * @param evt 
     */
    
    
    private void bReviewServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReviewServicesActionPerformed
        final JFrame frame = this;
                frame.setEnabled(false);
                frame.setAlwaysOnTop(false);
        //this.setVisible(false);
        ReviewServices services = new ReviewServices();
        services.setVisible(true);
        services.setLocationRelativeTo(null);
        services.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                frame.setEnabled(true);
                frame.setAlwaysOnTop(true);
            }
        });
        
        
        
        
        
    }//GEN-LAST:event_bReviewServicesActionPerformed

    /**
     * Opens the ReviewSongs Form so the user can review songs
     * @param evt 
     */
    private void bReviewSongsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReviewSongsActionPerformed
        ReviewSongs songs = new ReviewSongs();
        songs.setVisible(true);
    }//GEN-LAST:event_bReviewSongsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddItems;
    private javax.swing.JButton bCreateService;
    private javax.swing.JButton bDeleteItems;
    private javax.swing.JButton bEditItems;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bReviewServices;
    private javax.swing.JButton bReviewSongs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lLogo;
    private javax.swing.JLabel lTitle;
    // End of variables declaration//GEN-END:variables
}
